/** Platform-wide operational settings stored in `system_settings` (admin-managed). */
export const SYSTEM_SETTING_KEYS = {
  SEO_SITEMAP_CRON: 'SEO_SITEMAP_CRON',
  SITEMAP_ITEMS_PER_CHUNK: 'SITEMAP_ITEMS_PER_CHUNK',
  SEO_CANONICAL_APP_URL: 'SEO_CANONICAL_APP_URL',
  MARKETING_GTM_CONTAINER_ID: 'MARKETING_GTM_CONTAINER_ID',
  MARKETING_GA4_MEASUREMENT_ID: 'MARKETING_GA4_MEASUREMENT_ID',
  GEM_SCHEMA_VERSION: 'GEM_SCHEMA_VERSION',
  GEM_TRACKING_ENVIRONMENT: 'GEM_TRACKING_ENVIRONMENT',
  META_PIXEL_ID: 'META_PIXEL_ID',
  META_ACCESS_TOKEN: 'META_ACCESS_TOKEN',
  META_ANDROMEDA_DATA_PROCESSING_OPTIONS: 'META_ANDROMEDA_DATA_PROCESSING_OPTIONS',
  META_ANDROMEDA_COUNTRY: 'META_ANDROMEDA_COUNTRY',
  META_ANDROMEDA_STATE: 'META_ANDROMEDA_STATE',
  META_CAPI_DATA_SOURCE: 'META_CAPI_DATA_SOURCE',
  GOOGLE_SERVICES_CLIENT_EMAIL: 'GOOGLE_SERVICES_CLIENT_EMAIL',
  GOOGLE_SERVICES_PRIVATE_KEY: 'GOOGLE_SERVICES_PRIVATE_KEY',
} as const;

export type SystemSettingKey = (typeof SYSTEM_SETTING_KEYS)[keyof typeof SYSTEM_SETTING_KEYS];

const ALLOWED_KEYS = new Set<string>(Object.values(SYSTEM_SETTING_KEYS));

export function isAllowedSystemSettingKey(key: string): key is SystemSettingKey {
  return ALLOWED_KEYS.has(key);
}
